const currencies = {
    "brl": "Real Brasileiro",
    "usd": "Dolar dos Estados Unidos",
    "eur": "Euro",
    "jpy": "Yen japonês",
    "bob": "Bolivian boliviano",
    "ars": "Peso Argentino",
    "clp": "Peso Chileno",
    "cop": "Peso Colombiano",
    "cuc": "Peso Cubano",
    "uyu": "Peso Uruguaio",
    "aed": "Dirrã dos Emirados Árabes Unidos",
    "rub": "Rublo Russo",
    "ada": "Cardano",
    "afn": "Afghan afghani",
    "all": "Albanian lek",
    "amd": "Armenian dram",
    "amp": "Synereo",
    "ang": "Netherlands Antillean Guilder",
    "aoa": "Angolan kwanza",
    "aud": "Australian dollar",
    "awg": "Aruban florin",
    "axs": "AXS",
    "azn": "Azerbaijani manat",
    "bam": "Bosnia-Herzegovina Convertible Mark",
    "bat": "Basic Attention Token",
    "bbd": "Bajan dollar",
    "bch": "Bitcoin Cash",
    "bdt": "Bangladeshi taka",
    "bgn": "Bulgarian lev",
    "bhd": "Bahraini dinar",
    "bif": "Burundian Franc",
    "bmd": "Bermudan dollar",
    "bnb": "Binance Coin",
    "bnd": "Brunei dollar",
    "bsd": "Bahamian dollar",
    "bsv": "Bitcoin SV",
    "bsw": "Biswap",
    "btc": "Bitcoin",
    "btg": "Bitcoin Gold",
    "btn": "Bhutan currency",
    "bwp": "Botswanan Pula",
    "byn": "New Belarusian Ruble",
    "byr": "Belarusian Ruble",
    "bzd": "Belize dollar",
    "cad": "Canadian dollar",
    "cdf": "Congolese franc",
    "chf": "Swiss franc",
    "chz": "Chiliz",
    "cny": "Chinese Yuan",
    "crc": "Costa Rican Colón",
    "cro": "Crypto.com Chain Token",
    "crv": "Cravy",
    "cup": "Cuban Peso",
    "cve": "Cape Verdean escudo",
    "cvx": "Convex Finance",
    "czk": "Czech koruna",
    "dai": "Dai",
    "dcr": "Decred",
    "dfi": "DfiStarter",
    "djf": "Djiboutian franc",
    "dkk": "Danish krone",
    "dop": "Dominican peso",
    "dot": "Dotcoin",
    "dzd": "Algerian dinar",
    "egp": "Libra Egípcia",
    "enj": "Enjin Coin",
    "eos": "EOS",
    "ern": "Eritrean nakfa",
    "etb": "Ethiopian birr",
    "etc": "Ethereum Classic",
    "eth": "Ether",
    "fei": "Fei USD",
    "fil": "FileCoin",
    "fjd": "Fijian dollar",
    "fkp": "Falkland Islands pound",
    "ftm": "Fantom",
    "ftt": "FarmaTrust",
    "gbp": "Pound sterling",
    "gel": "Georgian lari",
    "ggp": "GGPro",
    "ghs": "Ghanaian cedi",
    "gip": "Gibraltar pound",
    "gmd": "Gambian dalasi",
    "gnf": "Guinean franc",
    "gno": "Gnosis",
    "grt": "Golden Ratio Token",
    "gtq": "Guatemalan quetzal",
    "gyd": "Guyanaese Dollar",
    "hkd": "Hong Kong dollar",
    "hnl": "Honduran lempira",
    "hnt": "Helium",
    "hot": "Hydro Protocol",
    "hrk": "Croatian kuna",
    "htg": "Haitian gourde",
    "huf": "Hungarian forint",
    "icp": "Internet Computer",
    "idr": "Indonesian rupiah",
    "ils": "Israeli New Shekel",
    "imp": "CoinIMP",
    "inj": "Injective",
    "inr": "Rupia indiana",
    "iqd": "Iraqi dinar",
    "irr": "Iranian rial",
    "isk": "Icelandic króna",
    "jep": "Jersey Pound",
    "jmd": "Jamaican dollar",
    "jod": "Jordanian dinar",
    "kcs": "Kucoin",
    "kda": "Kadena",
    "kes": "Kenyan shilling",
    "kgs": "Kyrgystani Som",
    "khr": "Cambodian riel",
    "kmf": "Comorian franc",
    "knc": "Kyber Network",
    "kpw": "won norte-coreano",
    "krw": "won sul-coreano",
    "ksm": "Kusama",
    "kwd": "Kuwaiti dinar",
    "kyd": "Cayman Islands dollar",
    "kzt": "Kazakhstani tenge",
    "lak": "Laotian Kip",
    "lbp": "Lebanese pound",
    "leo": "LEOcoin",
    "lkr": "Sri Lankan rupee",
    "lrc": "Loopring",
    "lrd": "Liberian dollar",
    "lsl": "Lesotho loti",
    "ltc": "Litecoin",
    "ltl": "Lithuanian litas",
    "lvl": "Latvian lats",
    "lyd": "Libyan dinar",
    "mad": "Moroccan dirham",
    "mdl": "Moldovan leu",
    "mga": "Malagasy ariary",
    "mkd": "Macedonian denar",
    "mkr": "Maker",
    "mmk": "Myanmar Kyat",
    "mnt": "Mongolian tugrik",
    "mop": "Macanese pataca",
    "mro": "Mauritanian ouguiya",
    "mur": "Mauritian rupee",
    "mvr": "Maldivian rufiyaa",
    "mwk": "Malawian kwacha",
    "mxn": "Mexican peso",
    "myr": "Malaysian ringgit",
    "mzn": "Mozambican Metical",
    "nad": "Namibian dollar",
    "neo": "NEO",
    "ngn": "Nigerian naira",
    "nio": "Nicaraguan córdoba",
    "nok": "Norwegian krone",
    "npr": "Nepalese rupee",
    "nzd": "New Zealand dollar",
    "okb": "Okex",
    "omr": "Omani rial",
    "one": "Menlo One",
    "pab": "Panamanian balboa",
    "pen": "Sol",
    "pgk": "Papua New Guinean kina",
    "php": "Philippine peso",
    "pkr": "Pakistani rupee",
    "pln": "Poland złoty",
    "pyg": "Paraguayan guarani",
    "qar": "Qatari Rial",
    "qnt": "Quant",
    "ron": "Romanian leu",
    "rsd": "Serbian dinar",
    "rwf": "Rwandan Franc",
    "sar": "Saudi riyal",
    "sbd": "Solomon Islands dollar",
    "scr": "Seychellois rupee",
    "sdg": "Sudanese pound",
    "sek": "Swedish krona",
    "sgd": "Singapore dollar",
    "shp": "Saint Helena pound",
    "sll": "Sierra Leonean leone",
    "sol": "Sola",
    "sos": "Somali shilling",
    "srd": "Surinamese dollar",
    "std": "São Tomé and Príncipe Dobra (pre-2018)",
    "stx": "Stox",
    "svc": "Salvadoran Colón",
    "syp": "Syrian pound",
    "szl": "Swazi lilangeni",
    "thb": "Thai baht",
    "tjs": "Tajikistani somoni",
    "tmt": "Turkmenistani manat",
    "tnd": "Tunisian dinar",
    "top": "Tongan Paʻanga",
    "trx": "TRON",
    "try": "Turkish lira",
    "ttd": "Trinidad & Tobago Dollar",
    "ttt": "Tap Project",
    "twd": "New Taiwan dollar",
    "tzs": "Tanzanian shilling",
    "uah": "Ukrainian hryvnia",
    "ugx": "Ugandan shilling",
    "uni": "Universe",
    "uzs": "Uzbekistani som",
    "vef": "Sovereign Bolivar",
    "vet": "Vechain",
    "vnd": "Vietnamese dong",
    "vuv": "Vanuatu vatu",
    "wst": "Samoan tala",
    "xaf": "Central African CFA franc",
    "xag": "Silver Ounce",
    "xau": "XauCoin",
    "xcd": "East Caribbean dollar",
    "xch": "Chia",
    "xdc": "XDC Network",
    "xdr": "Special Drawing Rights",
    "xec": "Eternal Coin",
    "xem": "NEM",
    "xlm": "Stellar",
    "xmr": "Monero",
    "xof": "West African CFA franc",
    "xpf": "CFP franc",
    "xrp": "XRP",
    "xtz": "Tezos",
    "yer": "Yemeni rial",
    "zar": "South African rand",
    "zec": "ZCash",
    "zil": "Zilliqa",
    "zmk": "Zambian kwacha",
    "zmw": "Zambian Kwacha",
    "zwl": "Zimbabwean Dollar"

}

export default currencies